myfirstproject/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('freightstore/', include('freightstore.urls')),
]

myfirstproject/freightstore/urls.py
from django.urls import path
from freightstore import views


urlpatterns = [
    path('', views.index, name='main'),
    path('maersk/', views.carriers, kwargs={'carr_id': 1}, name='maersk'),
    path('msc/', views.carriers, kwargs={'carr_id': 2}, name='msc'),
    path('cma_cgm/', views.carriers, kwargs={'carr_id': 3}, name='cma_cgm'),
    path('evergreen/', views.carriers, kwargs={'carr_id': 4}, name='evergreen'),
    path('hapag_lloyd/', views.carriers, kwargs={'carr_id': 5}, name='hapag_lloyd'),
]

myfirstproject/freightstore/models.py
from django.core.exceptions import ValidationError
from django.db import models
import re

#  export DYLD_LIBRARY_PATH="/usr/local/mysql/lib:$PATH"


class PositiveTinyAutoField(models.AutoField):
    def get_db_prep_value(self, value, connection, prepared=False):
        value = super().get_db_prep_value(value, connection, prepared)
        if not (0 <= value < 256):
            raise ValidationError('value of this field should be between 0 and 255')
        return value

    def db_type(self, connection):
        return 'tinyint unsigned auto_increment'

    def rel_db_type(self, connection):
        return 'tinyint unsigned'


class Carrier(models.Model):
    id = PositiveTinyAutoField(primary_key=True)
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'carrier'

    def __str__(self):
        return f'{self.name}'

    @property
    def short_name(self):
        s_name = re.sub('[^A-Za-z0-9]', '_', str(self.name))
        return str(s_name).lower()


class PortOfLoading(models.Model):
    id = PositiveTinyAutoField(primary_key=True)
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'port_of_loading'

    def __str__(self):
        return f'{self.name}'


class ContainerType(models.Model):
    id = PositiveTinyAutoField(primary_key=True)
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'container_type'

    def __str__(self):
        return f'{self.name}'


class FreightTariffs(models.Model):
    id = PositiveTinyAutoField(primary_key=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    carrier = models.ForeignKey(Carrier, models.CASCADE)
    port = models.ForeignKey(PortOfLoading, models.CASCADE)
    container = models.ForeignKey(ContainerType, models.CASCADE)

    class Meta:
        db_table = 'freight_tariffs'

    def __str__(self):
        return f'{self.price}'

myfirstproject/freightstore/views.py
from django.shortcuts import render
from freightstore.models import Carrier, PortOfLoading, ContainerType, FreightTariffs


def index(request):
    return render(
        request,
        'freightstore/homepage.html',
        {
            'carriers_list': Carrier.objects.all(),
            'ports_list': PortOfLoading.objects.all(),
            'containers_list': ContainerType.objects.all(),
            'tariffs_list': FreightTariffs.objects.all(),
        }
    )


def carriers(request, carr_id: int):
    carrier = Carrier.objects.get(pk=carr_id)
    return render(
        request,
        'freightstore/carriers.html',
        {
            'carrier':  carrier,
            'page_title': carrier.name,
        }
    )

myfirstproject/freightstore/templates/freightstore/carriers.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'styles/style.css'%}">
        <title>{{ page_title|default:'Домашняя страница' }}</title>
	</head>
	<body>
		<div>
			<div class="divmenu">
				<ul class="menu">
					<li><a href="{% url 'main' %}">Главная</a></li>
					<li><a href="">О компании</a></li>
					<li><a href="">Цены</a>
						<ul>
							{% for carrier in carriers_list %}
							<li><a href="{% url carrier.short_name %}">{{ carrier }}</a></li>
							{% endfor %}
						</ul>
					</li>
					<li><a href="">Контакты</a></li>
				</ul>
			</div>
			<div class="content">
				<h4>Порты</h4>
                <table>
					{{ carrier.id }}<br>
					{{ carrier.name }}
                    {% for tariff in carrier.freighttariffs_set.all %}
                    <tr>
                        {{ tariff }}
                    </tr>
                    {% endfor %}
                </table>
                <h4>Контейнеры</h4>
                <h4>цены</h4>
			</div>
		</div>
	</body>
</html>

myfirstproject/freightstore/templates/freightstore/homepage.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'styles/style.css'%}">
        <title>{{ page_title|default:'Домашняя страница' }}</title>
	</head>
	<body>
		<div>
			<div class="divmenu">
				<ul class="menu">
					<li><a href="{% url 'main' %}">Главная</a></li>
					<li><a href="">О компании</a></li>
					<li><a href="">Цены</a>
						<ul>
							{% for carrier in carriers_list %}
							<li><a href="{% url carrier.short_name %}">{{ carrier }}</a></li>
							{% endfor %}
						</ul>
					</li>
					<li><a href="">Контакты</a></li>
				</ul>
			</div>
			<div class="content">
			<h1>тут будет что то написано</h1>
			</div>
		</div>
		<footer>
			<hr>
			<p>FOOTER</p>
		</footer>
	</body>
</html>